Attribute VB_Name = "Function_Cikkszám_3"
Option Explicit

Sub Cikkszám_3()
Dim Fst As Integer, Snd As Integer, Trd As Integer, Foth As Integer, Fith As Integer, Sith As Integer, Seth As Integer, Eith As Integer, Nith As Integer
Fst = 1
Snd = 2
Trd = 3
Foth = 4
Fith = 5
Sith = 6
Seth = 7
Eith = 8
Nith = 9

' - harmadik tag

If AppCikkek.ComboBox4.Value = "" Then
Munka1.Range("z1").Value = 0
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("l4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("l5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("l6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("l7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("l8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("l9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("l10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("l11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("l12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("m4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("m5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("m6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("m7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("m8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("m9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("m10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("m11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("m12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("n4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("n5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("n6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("n7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("n8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("n9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("n10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("n11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("n12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("o4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("o5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("o6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("o7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("o8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("o9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("o10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("o11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("o12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("p4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("p5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("p6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("p7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("p8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("p9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("p10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("p11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("p12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("q4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("q5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("q6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("q7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("q8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("q9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("q10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("q11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("q12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("s4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("s5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("s6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("s7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("s8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("s9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("s10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("s11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("s12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("t4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("t5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("t6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("t7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("t8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("t9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("t10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("t11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("t12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("u4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("u5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("u6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("u7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("u8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("u9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("u10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("u11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("u12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("v4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("v5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("v6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("v7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("v8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("v9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("v10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("v11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("v12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("w4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("w5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("w6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("w7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("w8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("w9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("w10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("w11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("w12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("x4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("x5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("x6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("x7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("x8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("x9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("x10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("x11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("x12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("y4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("y5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("y6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("y7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("y8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("y9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("y10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("y11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("y12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("z12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aa4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aa5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aa6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aa7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aa8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aa9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aa10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aa11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aa12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ab4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ab5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ab6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ab7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ab8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ab9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ab10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ab11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ab12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ac4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ac5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ac6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ac7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ac8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ac9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ac10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ac11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ac12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ad4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ad5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ad6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ad7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ad8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ad9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ad10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ad11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ad12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ae4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ae5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ae6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ae7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ae8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ae9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ae10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ae11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ae12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("af4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("af5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("af6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("af7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("af8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("af9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("af10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("af11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("af12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ag4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ag5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ag6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ag7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ag8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ag9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ag10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ag11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ag12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ah4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ah5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ah6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ah7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ah8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ah9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ah10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ah11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ah12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ai4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ai5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ai6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ai7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ai8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ai9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ai10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ai11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ai12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aj4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aj5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aj6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aj7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aj8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aj9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aj10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aj11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aj12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ak4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ak5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ak6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ak7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ak8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ak9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ak10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ak11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ak12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("al4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("al5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("al6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("al7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("al8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("al9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("al10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("al11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("al12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("am4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("am5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("am6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("am7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("am8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("am9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("am10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("am11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("am12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("an4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("an5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("an6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("an7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("an8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("an9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("an10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("an11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("an12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ao4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ao5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ao6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ao7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ao8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ao9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ao10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ao11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ao12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ap4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ap5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ap6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ap7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ap8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ap9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ap10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ap11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ap12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aq4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aq5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aq6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aq7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aq8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aq9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aq10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aq11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aq12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ar4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ar5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ar6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ar7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ar8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ar9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ar10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ar11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ar12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("as4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("as5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("as6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("as7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("as8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("as9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("as10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("as11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("as12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("at4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("at5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("at6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("at7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("at8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("at9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("at10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("at11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("at12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("au4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("au5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("au6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("au7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("au8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("au9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("au10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("au11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("au12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("av4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("av5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("av6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("av7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("av8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("av9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("av10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("av11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("av12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aw4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aw5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aw6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aw7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aw8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aw9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aw10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aw11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("aw12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ax4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ax5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ax6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ax7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ax8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ax9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ax10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ax11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ax12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ay4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ay5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ay6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ay7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ay8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ay9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ay10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ay11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ay12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("az4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("az5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("az6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("az7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("az8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("az9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("az10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("az11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("az12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ba4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ba5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ba6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ba7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ba8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ba9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ba10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ba11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("ba12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bb4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bb5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bb6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bb7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bb8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bb9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bb10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bb11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bb12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bc4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bc5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bc6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bc7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bc8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bc9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bc10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bc11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bc12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bd4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bd5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bd6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bd7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bd8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bd9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bd10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bd11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bd12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("be4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("be5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("be6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("be7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("be8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("be9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("be10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("be11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("be12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bf4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bf5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bf6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bf7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bf8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bf9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bf10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bf11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bf12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bg4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bg5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bg6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bg7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bg8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bg9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bg10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bg11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bg12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bh4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bh5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bh6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bh7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bh8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bh9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bh10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bh11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bh12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bi4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bi5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bi6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bi7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bi8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bi9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bi10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bi11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bi12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bj4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bj5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bj6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bj7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bj8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bj9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bj10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bj11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bj12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bk4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bk5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bk6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bk7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bk8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bk9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bk10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bk11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bk12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bl4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bl5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bl6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bl7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bl8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bl9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bl10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bl11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bl12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bm4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bm5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bm6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bm7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bm8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bm9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bm10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bm11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bm12").Value Then
Munka1.Range("z1").Value = Nith

ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bn4").Value Then
Munka1.Range("z1").Value = Fst
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bn5").Value Then
Munka1.Range("z1").Value = Snd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bn6").Value Then
Munka1.Range("z1").Value = Trd
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bn7").Value Then
Munka1.Range("z1").Value = Foth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bn8").Value Then
Munka1.Range("z1").Value = Fith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bn9").Value Then
Munka1.Range("z1").Value = Sith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bn10").Value Then
Munka1.Range("z1").Value = Seth
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bn11").Value Then
Munka1.Range("z1").Value = Eith
ElseIf AppCikkek.ComboBox4.Value = Munka2.Range("bn12").Value Then
Munka1.Range("z1").Value = Nith
End If




End Sub
